// src/pages/Home.tsx

const Home = () => {

    return (
      <>
      <section className="min-w-full min-h-screen flex flex-col justify-evenly items-center">
        <h1 className="text-theme font-main font-bold text-2xl uppercase">React + Yarn template</h1>
      </section>
      </>
    )
  }
  
  export default Home

// src/routes/home/+page.svelte
<script lang="ts">
    let count = $state(0);

</script>

<div class="min-w-full min-h-screen flex flex-col justify-evenly items-center">
    This is Home page
    <button onclick={() => count += 1} class="bg-theme p-2 text-theme-w rounded-md hover:bg-theme-alt">Click: {count}</button>
    <a href="/" class="p-2 text-md rounded-md bg-theme hover:bg-theme-alt text-theme-w">Back</a>
</div>
