// src/components/Navbar.svelte
<script lang="ts">
	const navItems = ["Home", "Connect"]
</script>

<nav
	class="w-full p-2 fixed left-0 top-0 z-50 flex flex-row items-center justify-evenly shadow-md font-main-alt"
>
	{#each navItems as item, ind}
		<a href="/{item}" class="text-md text-theme hover:scale-105 font-bold uppercase" >{item}</a>
	{/each}
</nav>

// components/Navbar.tsx
import { _navItems } from '@/lib/data/_navItems'
import Link from 'next/link'
import React from 'react'

interface INavItem {
    title: string,
    url: string
};

const Navbar = () => {
  return (
    <nav className="flex flex-row justify-evenly items-center bg-white shadow-md text-theme font-bold">
        {
            _navItems.map((props, ind) => {
                return <NavItem key={ind} {...props} />
            })
        }
    </nav>
  )
}

const NavItem = ({title, url}: INavItem) => {
    return (
        <Link href={url} className="p-2 m-2 rounded-md hover:bg-theme-w-alt transition-colors duration-300">
            {title}
        </Link>
    )
}

export default Navbar
